[package]
name = "crypto-tests"
version = "0.1.0"
authors = ["Michał Śledź <sledzson08@gmail.com>"]
edition = "2018"

[dependencies]
ring="0.16.20"
criterion="0.3.4"
rand="0.8.3"
block-modes="0.7.0"
aes = "0.6.0"

[[bench]]
name="encryption"
harness=false
